export const EventsActionTypes = {
  GET: {
    GET_ALL_EVENTS_PENDING: "GET_ALL_EVENTS_PENDING",
    GET_ALL_EVENTS_SUCCESS: "GET_ALL_EVENTS_SUCCESS",
    GET_ALL_EVENTS_ERROR: "GET_ALL_EVENTS_ERROR",

    GET_EVENT_BY_ID_PENDING: "GET_EVENT_BY_ID_PENDING",
    GET_EVENT_BY_ID_SUCCESS: "GET_EVENT_BY_ID_SUCCESS",
    GET_EVENT_BY_ID_ERROR: "GET_EVENT_BY_ID_ERROR"
  },
  POST: {
    POST_EVENT_PENDING: "POST_EVENT_PENDING",
    POST_EVENT_SUCCESS: "POST_EVENT_SUCCESS",
    POST_EVENT_ERROR: "POST_EVENT_ERROR"
  },
  PUT: {
    PUT_EVENT_PENDING: "PUT_EVENT_PENDING",
    PUT_EVENT_SUCCESS: "PUT_EVENT_SUCCESS",
    PUT_EVENT_ERROR: "PUT_EVENT_ERROR"
  }
};
