export const UsersTypes = {
  GET: {
    GET_USERS_PENDING: "GET_USERS_PENDING",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_ERROR: "GET_USERS_ERROR",

    GET_USER_BY_ID_PENDING: "GET_USER_BY_ID_PENDING",
    GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",
    GET_USER_BY_ID_ERROR: "GET_USER_BY_ID_ERROR"
  },
  POST: {
    SIGN_UP_PENDING: "SIGN_UP_PENDING",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_ERROR: "SIGN_UP_ERROR"
  },
  CLEAR_USER_REQUEST_STATUS: "CLEAR_USER_REQUEST_STATUS"
};
