export const UsersTypes = {
  GET: {
    GET_USERS_PENDING: "GET_USERS_PENDING",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_ERROR: "GET_USERS_ERROR",

    GET_USER_BY_ID_PENDING: "GET_USER_BY_ID_PENDING",
    GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",
    GET_USER_BY_ID_ERROR: "GET_USER_BY_ID_ERROR",

    GET_USER_BY_NAME_PENDING: "GET_USER_BY_NAME_PENDING",
    GET_USER_BY_NAME_SUCCESS: "GET_USER_BY_NAME_SUCCESS",
    GET_USER_BY_NAME_ERROR: "GET_USER_BY_NAME_ERROR",

    SET_TO_STORE_MY_ACC: "SET_TO_STORE_MY_ACC"
  },
  POST: {
    SIGN_UP_PENDING: "SIGN_UP_PENDING",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_ERROR: "SIGN_UP_ERROR",

    SIGN_IN_PENDING: "SIGN_IN_PENDING",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_ERROR: "SIGN_IN_ERROR"
  },
  SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
  LOG_OUT_ACTION: "LOG_OUT_ACTION",
  CLEAR_USER_REQUEST_STATUS: "CLEAR_USER_REQUEST_STATUS"
};
